# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('short_name', models.CharField(max_length=128)),
                ('long_name', models.CharField(max_length=128)),
                ('city_kaz', models.CharField(blank=True, max_length=128, null=True)),
                ('city_rus', models.CharField(blank=True, max_length=128, null=True)),
                ('city_eng', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
