# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('car_type', models.CharField(max_length=30)),
                ('places', models.CharField(max_length=300)),
                ('tariff', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128)),
                ('express_id', models.CharField(max_length=128)),
                ('train', models.CharField(max_length=128)),
                ('departure_date', models.CharField(max_length=10)),
                ('departure_time', models.CharField(max_length=10)),
                ('arrival_date', models.CharField(max_length=10)),
                ('arrival_time', models.CharField(max_length=10)),
                ('departure_station', models.CharField(max_length=50)),
                ('arrival_station', models.CharField(max_length=50)),
                ('car_number', models.CharField(max_length=3)),
                ('car_type', models.CharField(max_length=20)),
                ('seat_number', models.CharField(max_length=3)),
                ('price', models.CharField(max_length=7)),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128)),
                ('direction', models.CharField(max_length=128)),
                ('departure_time', models.CharField(max_length=128)),
                ('arrival_time', models.CharField(max_length=128)),
                ('duration', models.CharField(max_length=128)),
                ('common_seats', models.CharField(max_length=128)),
                ('common_tariff', models.CharField(max_length=128)),
                ('sitting_seats', models.CharField(max_length=128)),
                ('sitting_tariff', models.CharField(max_length=128)),
                ('reserved_seats', models.CharField(max_length=128)),
                ('reserved_tariff', models.CharField(max_length=128)),
                ('compartment_seats', models.CharField(max_length=128)),
                ('compartment_tariff', models.CharField(max_length=128)),
                ('soft_seats', models.CharField(max_length=128)),
                ('soft_tariff', models.CharField(max_length=128)),
                ('luxury_seats', models.CharField(max_length=128)),
                ('luxury_tariff', models.CharField(max_length=128)),
            ],
        ),
    ]
